preset: "extended"
releasePrefix: v
git:
  remotes:
    origin:
      authenticationMethod: USER_PASSWORD
      user: "{{#environmentVariable}}REPOSITORY_OWNER{{/environmentVariable}}"
      password: "{{#environmentVariable}}AUTHENTICATION_TOKEN{{/environmentVariable}}"
releaseTypes:
  enabled: 
    - mainline  
  items:
    mainline:
      #collapseVersions: false
      #filterTags: "^v(\\d+)\\.(\\d+)\\.(\\d+)$"
      #gitCommit: false
      #gitCommitMessage: 'Release version'
      gitPush: true
      gitTag: true
      gitTagForce: true
      #matchBranches: "^(master|main)$"
      #matchWorkspaceStatus: "CLEAN"
      publish: true
  publicationServices: 
    - github
services: 
  github: 
    type: "GITHUB"
    options: 
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}AUTHENTICATION_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "{{#environmentVariable}}REPOSITORY_NAME{{/environmentVariable}}"
      REPOSITORY_OWNER: "{{#environmentVariable}}REPOSITORY_OWNER{{/environmentVariable}}"
