preset: "extended"
releasePrefix: v
releaseTypes:
  enabled: 
    - mainline  
  items:
    mainline:
      gitTagForce: true
      publish: true
  publicationServices: 
    - github
services: 
  github: 
    type: "GITHUB"
    options: 
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}AUTHENTICATION_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "{{#environmentVariable}}REPOSITORY_NAME{{/environmentVariable}}"
      REPOSITORY_OWNER: "{{#environmentVariable}}REPOSITORY_OWNER{{/environmentVariable}}"
