---
galaxy_info:
  author: Luis Novo
  description: Used to bootstrap config of every new host
  company: golili.net
  license: "Simplified BSD License"
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - impish
        - jammy
  galaxy_tags:
    - development
