---
- name: Install base packages
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - git
    - tig
    - htop
    - wget
    - tmux
    - vim
    - unzip
    - lnav
    - pydf
    - lfm
