---
- name: Add locales
  locale_gen:
    name: "{{item}}"
    state: present
  with_items:
    - en_US.UTF-8
    - es_ES.UTF-8

- name: Copy locales file
  copy:
    src: locale
    dest: /etc/default/locale

- name: Install base packages
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - git
    - tig
    - htop
    - wget
    - tmux
    - vim
    - unzip
    - lnav
    - pydf
    - lfm
    - httpie
    - bat
    - micro
    - exa
    - shellcheck
    - yadm
    - fzf
    - jq
    - python3-pip
