---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  
- name: Create user
  user:
    name: "{{admin_user}}"
    password: "{{admin_password|password_hash('sha512')}}"
    state: present
    generate_ssh_key: yes
    update_password: always
    shell: /bin/bash

- name: Add admin user to sudoers
  template:
    src: admin_sudoers
    dest: "/etc/sudoers.d/{{admin_user}}"
    owner: root
    group: root
    mode: 0440

- include_tasks: "{{ansible_os_family}}.yml"

- name: Set motd
  copy:
    src: motd
    dest: /etc
    owner: root
    group: root
    mode: 0644

- name: Custom prompt
  template:
    src: bashrc
    dest: "/home/{{admin_user}}/.bashrc"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"

- name: Enable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    line: 'PasswordAuthentication yes'
  notify: Restart sshd

- name: Enable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication no'
    line: 'ChallengeResponseAuthentication yes'
  notify: Restart sshd

- name: Download micro editor
  unarchive:
    src: https://github.com/zyedidia/micro/releases/download/v1.4.1/micro-1.4.1-linux64.tar.gz
    dest: /tmp
    remote_src: yes
    validate_certs: no
    creates: /tmp/micro-1.4.1

- name: Copy micro editor executable
  copy:
    src: /tmp/micro-1.4.1/micro
    dest: /usr/local/bin
    mode: 0755
    remote_src: yes

- name: Make sure required folder exists
  file:
    path: "/home/{{admin_user}}/.config/micro"
    state: directory
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0755    

- name: Copy micro editor settings
  copy:
    src: micro-settings.json
    dest: "/home/{{admin_user}}/.config/micro/settings.json"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Download bat
  unarchive:
    src: https://github.com/sharkdp/bat/releases/download/v0.10.0/bat-v0.10.0-x86_64-unknown-linux-musl.tar.gz
    dest: /tmp
    remote_src: yes
    validate_certs: no
    creates: /tmp/bat-v0.10.0-x86_64-unknown-linux-musl

- name: Copy bat executable
  copy:
    src: /tmp/bat-v0.10.0-x86_64-unknown-linux-musl/bat
    dest: /usr/local/bin
    mode: 0755
    remote_src: yes
