---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set timezone to Europe/Madrid
  community.general.timezone:
    name: Europe/Madrid

- name: Create user
  user:
    name: "{{admin_user}}"
    password: "{{admin_password|password_hash('sha512')}}"
    state: present
    generate_ssh_key: yes
    update_password: always
    shell: /bin/zsh

- name: Add admin user to sudoers
  template:
    src: admin_sudoers
    dest: "/etc/sudoers.d/{{admin_user}}"
    owner: root
    group: root
    mode: 0440

- include_tasks: "{{ansible_os_family}}.yml"

- name: Set motd
  copy:
    src: motd
    dest: /etc
    owner: root
    group: root
    mode: 0644

- name: Copy config files
  copy:
    src: "{{item}}"
    dest: "/home/{{admin_user}}/.{{item}}"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644
  with_items:
    - tmux.conf
    - gitconfig
    - gitignore

#- name: Enable ssh password authentication
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    regexp: '^PasswordAuthentication no'
#    line: 'PasswordAuthentication yes'
#  notify: Restart sshd
#
#- name: Enable ssh password authentication
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    regexp: '^ChallengeResponseAuthentication no'
#    line: 'ChallengeResponseAuthentication yes'
#  notify: Restart sshd

- name: Make sure config folders exist
  file:
    path: "/home/{{admin_user}}/.config/{{item}}"
    state: directory
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0755
  with_items:
    - micro
    - lfm
    - bat

- name: Copy micro editor settings
  copy:
    src: micro-settings.json
    dest: "/home/{{admin_user}}/.config/micro/settings.json"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Copy lfm file manager settings
  copy:
    src: lfm.ini
    dest: "/home/{{admin_user}}/.config/lfm/lfm.ini"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Copy bat settings
  copy:
    src: batconfig
    dest: "/home/{{admin_user}}/.config/bat/config"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Copy command alternatives
  copy:
    src: "{{item}}"
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - hr

- name: Install tools
  unarchive:
    src: "{{item.value}}"
    dest: /usr/local/bin/
    remote_src: yes
    validate_certs: no
    owner: root
    group: root
    mode: 0755
  with_dict: "{{tools}}"

- name: Donwload fzf extra stuff
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{fzf_dir}}"
    depth: 1

- name: Install yq
  get_url:
    url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    dest: /usr/local/bin/yq
    owner: root
    group: root
    mode: 0755
    validate_certs: no

- name: Install required python modules
  pip:
    name: "{{pip_packages}}"
