---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create user
  user:
    name: "{{admin_user}}"
    password: "{{admin_password|password_hash('sha512')}}"
    state: present
    generate_ssh_key: yes
    update_password: always
    shell: /bin/zsh

- name: Add admin user to sudoers
  template:
    src: admin_sudoers
    dest: "/etc/sudoers.d/{{admin_user}}"
    owner: root
    group: root
    mode: 0440

- include_tasks: "{{ansible_os_family}}.yml"

- name: Set motd
  copy:
    src: motd
    dest: /etc
    owner: root
    group: root
    mode: 0644

- name: Enable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    line: 'PasswordAuthentication yes'
  notify: Restart sshd

- name: Enable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication no'
    line: 'ChallengeResponseAuthentication yes'
  notify: Restart sshd

- name: Make sure config folders exist
  file:
    path: "/home/{{admin_user}}/.config/{{item}}"
    state: directory
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0755
  with_items:
    - micro
    - lfm

- name: Copy micro editor settings
  copy:
    src: micro-settings.json
    dest: "/home/{{admin_user}}/.config/micro/settings.json"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Copy lfm file manager settings
  copy:
    src: lfm.ini
    dest: "/home/{{admin_user}}/.config/lfm/lfm.ini"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Copy command alternatives
  copy:
    src: "{{item}}"
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - hr

- name: Install procs
  unarchive:
    src: "https://github.com/dalance/procs/releases/download/{{procs_version}}/procs-{{procs_version}}-x86_64-lnx.zip"
    dest: /usr/local/bin/
    remote_src: yes
    validate_certs: no

- name: Install gdu
  unarchive:
    src: "https://github.com/dundee/gdu/releases/download/{{gdu_version}}/gdu_linux_amd64.tgz"
    dest: /usr/local/bin/
    remote_src: yes
    validate_certs: no

- name: Install fzf
  unarchive:
    src: "https://github.com/junegunn/fzf/releases/download/0.27.0/fzf-0.27.0-linux_amd64.tar.gz"
    dest: /usr/local/bin/
    remote_src: yes
    validate_certs: no

- name: Install navi
  unarchive:
    src: "https://github.com/denisidoro/navi/releases/download/v2.16.0/navi-v2.16.0-x86_64-unknown-linux-musl.tar.gz"
    dest: /usr/local/bin/
    remote_src: yes
    validate_certs: no
