---
- name: Enable EPEL Repos
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install base packages
  yum:
    name: 
      - git
      - mc
      - htop
      - wget
      - tmux
      - vim
      - unzip
      - lnav
      - python-pip
    state: present
    disable_gpg_check: yes

- name: Install pydf via pip
  pip:
    name: pydf
