---
- name: Disable yum gpg check
  lineinfile:
    path: /etc/yum.conf
    regexp: '^gpgcheck=1'
    line: 'gpgcheck=0'

- name: Enable EPEL Repos
  yum:
    name:
      - epel-release
    state: present
    validate_certs: no

- name: Install base packages
  yum:
    name:
      - git
      - tig
      - htop
      - wget
      - tmux
      - vim
      - unzip
      - lnav
      - httpie
    state: present
    disable_gpg_check: yes

- name: Install (dnf) base packages
  dnf:
    name:
      - python3
    state: present

- name: Install required python modules
  pip:
    name: "{{pip_packages}}"
    executable: /usr/bin/pip3
