---
- name: Disable yum gpg check
  lineinfile:
    path: /etc/yum.conf
    regexp: '^gpgcheck=1'
    line: 'gpgcheck=0'

- name: Enable EPEL Repos
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install base packages
  yum:
    name:
      - git
      - tig
      - mc
      - htop
      - wget
      - tmux
      - vim
      - unzip
      - lnav
      - zsh
    #  - python-pip
      - python3
    state: present
    disable_gpg_check: yes

#- name: Install pydf via pip
#  pip:
#    name: pydf

- name: Install pip packages
  pip:
    executable: /bin/pip3
    name:
      - pydf
      - lfm
