---
- name: Disable yum gpg check
  lineinfile:
    path: /etc/yum.conf
    regexp: '^gpgcheck=1'
    line: 'gpgcheck=0'

#- name: Enable EPEL Repos
#  yum_repository:
#    name: epel
#    description: EPEL YUM repo
#    baseurl: https://download.fedoraproject.org/pub/epel/8/Everything/x86_64/

#- name: Enable EPEL Repos
#  yum:
#    name: epel-release
#    state: present
#    validate_certs: no

- name: Install base packages
  yum:
    name:
      - epel-release
      - git
      - tig
      - htop
      - wget
      - tmux
      - vim
      - unzip
    #  - python-pip
    state: present
    disable_gpg_check: yes

- name: Install (dnf) base packages
  dnf:
    name:
      - python3
    state: present
