---
- name: Install delta .deb package
  ansible.builtin.apt:
    deb: "{{delta_url}}"

- name: Copy config files
  copy:
    src: "{{item}}"
    dest: "/home/{{admin_user}}/.{{item}}"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644
  with_items:
    - tmux.conf
    - gitconfig
    - gitignore_global

- name: Make sure config folders exist
  file:
    path: "/home/{{admin_user}}/.config/{{item}}"
    state: directory
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0755
  with_items:
    - micro
    - lfm
    - bat
    - lnav

- name: Copy micro editor settings
  copy:
    src: micro-settings.json
    dest: "/home/{{admin_user}}/.config/micro/settings.json"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Copy lfm file manager settings
  copy:
    src: lfm.ini
    dest: "/home/{{admin_user}}/.config/lfm/lfm.ini"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Copy bat settings
  copy:
    src: batconfig
    dest: "/home/{{admin_user}}/.config/bat/config"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Copy lnav settings
  copy:
    src: lnav_config.json
    dest: "/home/{{admin_user}}/.config/lnav/config.json"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644

- name: Copy command alternatives
  copy:
    src: "{{item}}"
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - hr

- name: Install tools
  unarchive:
    src: "{{item.value}}"
    dest: /usr/local/bin/
    remote_src: yes
    validate_certs: no
    owner: root
    group: root
    mode: 0755
  with_dict: "{{tools}}"

- name: Donwload fzf extra stuff
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{fzf_dir}}"
    depth: 1

- name: Install yq
  get_url:
    url: "{{yq_url}}"
    dest: /usr/local/bin/yq
    owner: root
    group: root
    mode: 0755
    validate_certs: no

- name: Install required python modules
  community.general.pipx:
    name: "{{item}}"
  with_items: "{{pip_packages}}"

#- name: Install dysk
#  unarchive:
#    src: https://github.com/Canop/dysk/releases/download/v2.8.2/dysk_2.8.2.zip
#    dest: /usr/local/bin/
#    creates: /usr/local/bin/dysk
#    include:
#    - build/x86_64-linux/dysk
#    remote_src: yes
#    validate_certs: no
#    extra_opts:
#    - -j

- name: Remove lazynvim dir if previously installed
  file:
    path: "/home/{{admin_user}}/.config/nvim"
    state: absent
    
- name: Install lazyvim
  ansible.builtin.git:
    repo: https://github.com/LazyVim/starter
    dest: "/home/{{admin_user}}/.config/nvim"
    update: yes
  become: yes
  become_user: "{{admin_user}}"

- name: Remove .git from LazyVim installation
  file:
    path: "/home/{{admin_user}}/.config/nvim/.git"
    state: absent

- name: Copy lazyvim color scheme
  copy:
    src: colorscheme.lua
    dest: "/home/{{admin_user}}/.config/nvim/lua/plugins"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
    mode: 0644
