alias ls='ls --color=auto --group-directories-first'
alias ll='ls -l'
alias la='ls -la'
alias mi='micro'
alias cat='bat'
alias df='pydf -a'

export PS1='[\[\033[01;32m\]\u@\h\[\033[01;34m\] $PWD]\$\[\033[00m\] '
export MICRO_TRUECOLOR=1
function cd() {
  new_directory="$*";
  if [ $# -eq 0 ]; then 
    new_directory=${HOME};
  fi;
  builtin cd "${new_directory}" && ls -l
}
