# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory extendedglob nomatch notify
unsetopt autocd beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/admin/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Custom aliases
alias cat='bat'
alias mi='micro'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -l'
alias la='ls -la'
alias tf='tail -f'
alias hr='hr "-"'

# Custom environment variables
export EDITOR=micro
export MICRO_TRUECOLOR=1

PROMPT='[%F{082}%n@%M %F{033}%d%F{255}]%F{226}$(_git_branch_name)%F{255}$ '
