name: Release process
on:
  push:
jobs:
  release:
    name: Perform release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Tag repo
      id: nyx
      uses: mooltiverse/nyx-github-action@main
      #env:
      #  AUTHENTICATION_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #  REPOSITORY_NAME: common-ansible-role
      #  REPOSITORY_OWNER: capitanh        
      with:
        preset: "extended"
        releasePrefix: v        
        command: mark
  #galaxy-import:
  #  name: Publish on Ansible Galaxy
  #  runs-on: ubuntu-latest
  #  needs: gradle-release
  #  steps:
  #  - name: Checkout project sources
  #    uses: actions/checkout@v3
  #    with:
  #      fetch-depth: 0      
  #  - name: Release Ansible Role to Galaxy
  #    uses: hspaans/ansible-galaxy-action@v1
  #    with:
  #      api_key: ${{secrets.ANSIBLE_GALAXY_API_KEY}}
