name: Release process
on:
  push:
jobs:
  release:
    name: Perform gradle release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Tag repo
      id: nyx
      uses: mooltiverse/nyx-github-action@main
      env:
        GH_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      with:
        command: 'mark'
        preset: "extended"
        releasePrefix: v        
  #galaxy-import:
  #  name: Publish on Ansible Galaxy
  #  runs-on: ubuntu-latest
  #  needs: gradle-release
  #  steps:
  #  - name: Checkout project sources
  #    uses: actions/checkout@v3
  #    with:
  #      fetch-depth: 0      
  #  - name: Release Ansible Role to Galaxy
  #    uses: hspaans/ansible-galaxy-action@v1
  #    with:
  #      api_key: ${{secrets.ANSIBLE_GALAXY_API_KEY}}
